/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    application
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://jitpack.io")
    }
}

dependencies {
    api(libs.org.jfree.jfreechart)
    api(libs.org.jfree.jcommon)
    implementation("com.github.crazzyghost:alphavantage-java:1.7.0")
}

group = "com.yourcompany.yourapp"
version = "1.0-SNAPSHOT"
description = "StockSim"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
application {
    mainClass.set("Main")
}